# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About Me"
  pageRef = "about"
  title = "Learn more about Socrates"
  weight = 10

[[main]]
  name = "Tech Journal"
  pageRef = "tech-journal"
  title = "Explore my technical articles and insights"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  title = "See my portfolio of projects"
  weight = 30

[[main]]
  identifier = "search"
  weight = 40
  [main.params]
    action = "search"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.
[[footer]]
  name = "Index"
  pageRef = "tags"
  weight = 10
  [footer.params]
    icon = "bars"
    showName = true
    # target = "_blank" # opens in a new tab


# [[footer]]
#   name = "GitHub"
#   url = "https://github.com/socrabytes"
#   weight = 20
#   [footer.params]
#     icon = "github"
#     showName = true
#     target = "_blank"

# [[footer]]
#   name = "LinkedIn"
#   url = "https://linkedin.com/in/socrateslopez"
#   weight = 30
#   [footer.params]
#     icon = "linkedin"
#     showName = true
#     target = "_blank"     

[[footer]]
  identifier = "search"
  weight = 40
  [footer.params]
    action = "search"
    icon = "search"

# [[footer]]
#   name = "Privacy"
#   pageRef = "privacy"
#   weight = 20

# [[footer]]
#   name = "Terms"
#   pageRef = "terms"
#   weight = 30

# [[footer]]
#   name = "Contact"
#   pageRef = "contact"
#   weight = 40